---
- name: reload user systemd
  ansible.builtin.command: systemctl --user daemon-reload
  become: true
  become_user: "{{ deploy_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ deploy_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ deploy_uid }}/bus"
  changed_when: true

- name: restart solrise
  ansible.builtin.command: systemctl --user restart solrise.service
  become: true
  become_user: "{{ deploy_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ deploy_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ deploy_uid }}/bus"
  changed_when: true
